export const mockData = [
  {
    id: "Q7OkRjnqIJmeZJHCnbnIcA",
    alias: "bertucellis-la-villa-san-jose",
    name: "Bertucelli's La Villa",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/fJFblQC0s4fdNwJ_GCKf4A/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/bertucellis-la-villa-san-jose?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 1463,
    categories: [
      { alias: "sandwiches", title: "Sandwiches" },
      { alias: "italian", title: "Italian" },
    ],
    rating: 4.3,
    coordinates: { latitude: 37.30458, longitude: -121.89858 },
    transactions: ["pickup", "delivery"],
    price: "$$",
    location: {
      address1: "1319 Lincoln Ave",
      address2: "",
      address3: "",
      city: "San Jose",
      zip_code: "95125",
      country: "US",
      state: "CA",
      display_address: ["1319 Lincoln Ave", "San Jose, CA 95125"],
    },
    phone: "+14082957851",
    display_phone: "(408) 295-7851",
    distance: 1779.8327220681333,
  },
  {
    id: "zLViW6kDKNLIYsGkBCNorg",
    alias: "paesano-ristorante-italiano-san-jose",
    name: "Paesano Ristorante Italiano",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/Tz4UAMDiTgIAqNznwZgevQ/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/paesano-ristorante-italiano-san-jose?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 1358,
    categories: [{ alias: "italian", title: "Italian" }],
    rating: 4.1,
    coordinates: { latitude: 37.336166540678, longitude: -121.89867135144 },
    transactions: ["delivery"],
    price: "$$",
    location: {
      address1: "350 W Julian St",
      address2: "Ste 1",
      address3: "",
      city: "San Jose",
      zip_code: "95110",
      country: "US",
      state: "CA",
      display_address: ["350 W Julian St", "Ste 1", "San Jose, CA 95110"],
    },
    phone: "+14082179327",
    display_phone: "(408) 217-9327",
    distance: 2497.5070746721076,
  },
  {
    id: "nZyCo-rCRN_dFFuQ50HJPQ",
    alias: "cafe-dolce-sicilia-san-jose-2",
    name: "Cafe Dolce Sicilia",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/HKY-3bzgNpu4Pa9BAE6i8g/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/cafe-dolce-sicilia-san-jose-2?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 203,
    categories: [
      { alias: "desserts", title: "Desserts" },
      { alias: "italian", title: "Italian" },
      { alias: "pastashops", title: "Pasta Shops" },
    ],
    rating: 4.7,
    coordinates: { latitude: 37.30717, longitude: -121.90076 },
    transactions: ["pickup", "delivery"],
    price: "$",
    location: {
      address1: "1165 Lincoln Ave",
      address2: "Ste 110",
      address3: "",
      city: "San Jose",
      zip_code: "95125",
      country: "US",
      state: "CA",
      display_address: ["1165 Lincoln Ave", "Ste 110", "San Jose, CA 95125"],
    },
    phone: "+14088823953",
    display_phone: "(408) 882-3953",
    distance: 1724.4921976135604,
  },
  {
    id: "w8taOB25WBct_YBsuqc4vQ",
    alias: "la-casa-mia-santa-clara",
    name: "La Casa Mia",
    image_url:
      "https://s3-media4.fl.yelpcdn.com/bphoto/VmlNu4GA5wp_9ASUOnZ77g/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/la-casa-mia-santa-clara?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 637,
    categories: [
      { alias: "japanese", title: "Japanese" },
      { alias: "italian", title: "Italian" },
    ],
    rating: 3.9,
    coordinates: { latitude: 37.33625, longitude: -121.99419 },
    transactions: [],
    price: "$$",
    location: {
      address1: "3548 Homestead Rd",
      address2: null,
      address3: "",
      city: "Santa Clara",
      zip_code: "95051",
      country: "US",
      state: "CA",
      display_address: ["3548 Homestead Rd", "Santa Clara, CA 95051"],
    },
    phone: "+16506031277",
    display_phone: "(650) 603-1277",
    distance: 9901.14877323436,
  },
  {
    id: "TeBae7JAYIptn37IqzngEw",
    alias: "luigis-pizza-and-pasta-campbell",
    name: "Luigi's Pizza & Pasta",
    image_url:
      "https://s3-media1.fl.yelpcdn.com/bphoto/rY7cTwPFW_lkUrnoH6Hx6A/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/luigis-pizza-and-pasta-campbell?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 845,
    categories: [
      { alias: "pizza", title: "Pizza" },
      { alias: "italian", title: "Italian" },
    ],
    rating: 4.3,
    coordinates: { latitude: 37.278512215687, longitude: -121.950654435721 },
    transactions: ["pickup", "delivery"],
    price: "$$",
    location: {
      address1: "2495 Winchester Blvd",
      address2: "",
      address3: "",
      city: "Campbell",
      zip_code: "95008",
      country: "US",
      state: "CA",
      display_address: ["2495 Winchester Blvd", "Campbell, CA 95008"],
    },
    phone: "+14083786862",
    display_phone: "(408) 378-6862",
    distance: 7174.8953301384745,
  },
  {
    id: "zXQF2Z_tyujpn9hJlJhURQ",
    alias: "antipastos-by-derose-gourmet-meat-fish-and-deli-san-jose",
    name: "Antipasto's By Derose Gourmet Meat Fish & Deli",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/cz4PKevCEGTlutQZm6i2BQ/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/antipastos-by-derose-gourmet-meat-fish-and-deli-san-jose?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 1097,
    categories: [
      { alias: "delis", title: "Delis" },
      { alias: "italian", title: "Italian" },
      { alias: "beerbar", title: "Beer Bar" },
    ],
    rating: 4.5,
    coordinates: { latitude: 37.3801496200615, longitude: -121.827435493469 },
    transactions: ["delivery"],
    price: "$$",
    location: {
      address1: "3454 McKee Rd",
      address2: "",
      address3: "",
      city: "San Jose",
      zip_code: "95127",
      country: "US",
      state: "CA",
      display_address: ["3454 McKee Rd", "San Jose, CA 95127"],
    },
    phone: "+14082515647",
    display_phone: "(408) 251-5647",
    distance: 8722.204256696978,
  },
  {
    id: "i50BEr4Pq6-D8tmsegmVyA",
    alias: "the-table-san-jose",
    name: "The Table",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/UhM-Z47tZ8SGX663NwFr3g/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/the-table-san-jose?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 3766,
    categories: [
      { alias: "newamerican", title: "New American" },
      { alias: "breakfast_brunch", title: "Breakfast & Brunch" },
      { alias: "salad", title: "Salad" },
    ],
    rating: 3.9,
    coordinates: { latitude: 37.308203, longitude: -121.901284 },
    transactions: ["delivery"],
    price: "$$",
    location: {
      address1: "1110 Willow St",
      address2: "",
      address3: "",
      city: "San Jose",
      zip_code: "95125",
      country: "US",
      state: "CA",
      display_address: ["1110 Willow St", "San Jose, CA 95125"],
    },
    phone: "+14086387911",
    display_phone: "(408) 638-7911",
    distance: 1703.8956839531236,
  },
  {
    id: "5uc07F6ztscpuPTQdmUZsg",
    alias: "sorelle-italian-bistro-campbell",
    name: "Sorelle Italian Bistro",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/MWSbuqwaXIAkaNtF-_0Q3w/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/sorelle-italian-bistro-campbell?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 876,
    categories: [{ alias: "italian", title: "Italian" }],
    rating: 4.4,
    coordinates: { latitude: 37.273802, longitude: -121.971816 },
    transactions: ["delivery"],
    price: "$$",
    location: {
      address1: "915 S San Tomas Aquino Rd",
      address2: "",
      address3: "",
      city: "Campbell",
      zip_code: "95008",
      country: "US",
      state: "CA",
      display_address: ["915 S San Tomas Aquino Rd", "Campbell, CA 95008"],
    },
    phone: "+14083741800",
    display_phone: "(408) 374-1800",
    distance: 9022.283702165643,
  },
  {
    id: "T5_NWh4DF6jtn41yuNZmwQ",
    alias: "blossom-and-bourbon-san-jose",
    name: "Blossom & Bourbon",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/6jGVK2gRp4qHi3SWCihFXg/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/blossom-and-bourbon-san-jose?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 407,
    categories: [
      { alias: "tradamerican", title: "American" },
      { alias: "cocktailbars", title: "Cocktail Bars" },
      { alias: "whiskeybars", title: "Whiskey Bars" },
    ],
    rating: 4.2,
    coordinates: { latitude: 37.2501805, longitude: -121.8449315 },
    transactions: [],
    price: "$$$",
    location: {
      address1: "632 Blossom Hill Rd",
      address2: null,
      address3: "",
      city: "San Jose",
      zip_code: "95123",
      country: "US",
      state: "CA",
      display_address: ["632 Blossom Hill Rd", "San Jose, CA 95123"],
    },
    phone: "+14088188444",
    display_phone: "(408) 818-8444",
    distance: 8184.746051944369,
  },
  {
    id: "1gUlwDbkVOz4xjaAjy4NDg",
    alias: "il-fornaio-santa-clara-2",
    name: "Il Fornaio",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/wCsESggGPDj4a3V2PkNzEA/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/il-fornaio-santa-clara-2?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 2162,
    categories: [
      { alias: "pizza", title: "Pizza" },
      { alias: "seafood", title: "Seafood" },
      { alias: "italian", title: "Italian" },
    ],
    rating: 4.2,
    coordinates: { latitude: 37.3822051, longitude: -121.9767941 },
    transactions: ["pickup", "delivery"],
    price: "$$$",
    location: {
      address1: "2752 Augustine Dr",
      address2: "Ste 120",
      address3: null,
      city: "Santa Clara",
      zip_code: "95054",
      country: "US",
      state: "CA",
      display_address: [
        "2752 Augustine Dr",
        "Ste 120",
        "Santa Clara, CA 95054",
      ],
    },
    phone: "+14082178844",
    display_phone: "(408) 217-8844",
    distance: 10839.270152880837,
  },
  {
    id: "806-vIK9uofrSqPmow0ySQ",
    alias: "maggianos-little-italy-san-jose",
    name: "Maggiano's Little Italy",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/D4GvJ8oJz0f8ZUuUdCuy9g/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/maggianos-little-italy-san-jose?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 4592,
    categories: [
      { alias: "italian", title: "Italian" },
      { alias: "salad", title: "Salad" },
      { alias: "seafood", title: "Seafood" },
    ],
    rating: 3.4,
    coordinates: { latitude: 37.320785118349, longitude: -121.949700120446 },
    transactions: ["pickup", "delivery"],
    price: "$$",
    location: {
      address1: "3055 Olin Ave",
      address2: "Ste 1000",
      address3: "",
      city: "San Jose",
      zip_code: "95128",
      country: "US",
      state: "CA",
      display_address: ["3055 Olin Ave", "Ste 1000", "San Jose, CA 95128"],
    },
    phone: "+14084238973",
    display_phone: "(408) 423-8973",
    distance: 5735.211863959074,
  },
  {
    id: "N7_ghbJDwMx_NrG43DlQZA",
    alias: "palermo-italian-restaurant-san-jose-3",
    name: "Palermo Italian Restaurant",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/wSl8YjxyD5qQw1xkYXNYkg/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/palermo-italian-restaurant-san-jose-3?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 766,
    categories: [
      { alias: "italian", title: "Italian" },
      { alias: "pizza", title: "Pizza" },
      { alias: "delis", title: "Delis" },
    ],
    rating: 4.2,
    coordinates: { latitude: 37.32184, longitude: -121.90239 },
    transactions: ["pickup", "delivery"],
    price: "$$",
    location: {
      address1: "791 Auzerais Ave",
      address2: "",
      address3: null,
      city: "San Jose",
      zip_code: "95126",
      country: "US",
      state: "CA",
      display_address: ["791 Auzerais Ave", "San Jose, CA 95126"],
    },
    phone: "+14082956459",
    display_phone: "(408) 295-6459",
    distance: 1631.923317140323,
  },
  {
    id: "uYcvTFXCm4YMwzR7UqWE6w",
    alias: "italian-brothers-restaurant-los-gatos",
    name: "Italian Brothers Restaurant",
    image_url:
      "https://s3-media1.fl.yelpcdn.com/bphoto/U8vWtiP-TtEOq_sXIyjcTA/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/italian-brothers-restaurant-los-gatos?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 459,
    categories: [{ alias: "italian", title: "Italian" }],
    rating: 4.3,
    coordinates: { latitude: 37.22824, longitude: -121.98107 },
    transactions: ["pickup", "delivery"],
    price: "$$",
    location: {
      address1: "330 N Santa Cruz Ave",
      address2: "",
      address3: null,
      city: "Los Gatos",
      zip_code: "95030",
      country: "US",
      state: "CA",
      display_address: ["330 N Santa Cruz Ave", "Los Gatos, CA 95030"],
    },
    phone: "+14083540111",
    display_phone: "(408) 354-0111",
    distance: 12986.716165966025,
  },
  {
    id: "s9VWmvc0Sd8OQV_8R7g-Cg",
    alias: "pasta-fresca-san-jose-3",
    name: "Pasta Fresca",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/FGR3PPgKA_c4QITLf1rQsQ/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/pasta-fresca-san-jose-3?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 163,
    categories: [{ alias: "italian", title: "Italian" }],
    rating: 3.6,
    coordinates: { latitude: 37.33651, longitude: -121.89432 },
    transactions: ["delivery"],
    price: "$$",
    location: {
      address1: "87 N San Pedro St",
      address2: null,
      address3: "",
      city: "San Jose",
      zip_code: "95110",
      country: "US",
      state: "CA",
      display_address: ["87 N San Pedro St", "San Jose, CA 95110"],
    },
    phone: "+16508046260",
    display_phone: "(650) 804-6260",
    distance: 2375.7859401127166,
  },
  {
    id: "bFRyCPb1OU7MYyY4CR3qKQ",
    alias: "rollati-ristorante-san-jose",
    name: "Rollati Ristorante",
    image_url:
      "https://s3-media4.fl.yelpcdn.com/bphoto/uWLx60u7hNMpciklJBhbtw/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/rollati-ristorante-san-jose?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 366,
    categories: [
      { alias: "italian", title: "Italian" },
      { alias: "pastashops", title: "Pasta Shops" },
      { alias: "pizza", title: "Pizza" },
    ],
    rating: 3.9,
    coordinates: { latitude: 37.3379716028814, longitude: -121.8872292689838 },
    transactions: [],
    price: "$$$",
    location: {
      address1: "181 East Santa Clara St",
      address2: "",
      address3: "",
      city: "San Jose",
      zip_code: "95113",
      country: "US",
      state: "CA",
      display_address: ["181 East Santa Clara St", "San Jose, CA 95113"],
    },
    phone: "+14084444080",
    display_phone: "(408) 444-4080",
    distance: 2397.235544172413,
  },
  {
    id: "1VcX2Z35wjE2ztBOKF-AvA",
    alias: "ristorante-da-maria-san-jose-2",
    name: "Ristorante da Maria",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/qy2LG6N7NSekI-5ebKJX3w/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/ristorante-da-maria-san-jose-2?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 683,
    categories: [
      { alias: "pizza", title: "Pizza" },
      { alias: "italian", title: "Italian" },
    ],
    rating: 4.1,
    coordinates: { latitude: 37.272161, longitude: -121.933931 },
    transactions: ["pickup", "delivery"],
    price: "$$",
    location: {
      address1: "2707 Union Ave",
      address2: "",
      address3: null,
      city: "San Jose",
      zip_code: "95124",
      country: "US",
      state: "CA",
      display_address: ["2707 Union Ave", "San Jose, CA 95124"],
    },
    phone: "+14083713333",
    display_phone: "(408) 371-3333",
    distance: 6554.9756908534055,
  },
  {
    id: "yk4sQvYhp50HZRP7zaIZFg",
    alias: "locanda-sorrento-campbell",
    name: "Locanda Sorrento",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/dcL8-ncsubiYXfXQ_eB6eg/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/locanda-sorrento-campbell?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 756,
    categories: [
      { alias: "italian", title: "Italian" },
      { alias: "pizza", title: "Pizza" },
      { alias: "cocktailbars", title: "Cocktail Bars" },
    ],
    rating: 4.1,
    coordinates: { latitude: 37.286926, longitude: -121.948293 },
    transactions: [],
    price: "$$",
    location: {
      address1: "76 E Campbell Ave",
      address2: null,
      address3: "",
      city: "Campbell",
      zip_code: "95008",
      country: "US",
      state: "CA",
      display_address: ["76 E Campbell Ave", "Campbell, CA 95008"],
    },
    phone: "+14085407686",
    display_phone: "(408) 540-7686",
    distance: 6488.7438163582065,
  },
  {
    id: "DgFC8cq7QTg36lkKhhSzAw",
    alias: "the-pastaria-and-market-los-gatos",
    name: "The Pastaria & Market",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/l2rVmy0AP0mLxcCUmFsLbw/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/the-pastaria-and-market-los-gatos?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 944,
    categories: [
      { alias: "italian", title: "Italian" },
      { alias: "wine_bars", title: "Wine Bars" },
    ],
    rating: 4.2,
    coordinates: { latitude: 37.22352, longitude: -121.98384 },
    transactions: ["delivery"],
    price: "$$",
    location: {
      address1: "27 N Santa Cruz",
      address2: "",
      address3: "",
      city: "Los Gatos",
      zip_code: "95030",
      country: "US",
      state: "CA",
      display_address: ["27 N Santa Cruz", "Los Gatos, CA 95030"],
    },
    phone: "+14083993477",
    display_phone: "(408) 399-3477",
    distance: 13533.669412817024,
  },
  {
    id: "WjoA8JyAUQp_AdhLq40Udg",
    alias: "the-creek-eatery-san-jose",
    name: "The Creek Eatery",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/Nk-1M_LW9uQu-joUdtuF5w/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/the-creek-eatery-san-jose?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 474,
    categories: [
      { alias: "wine_bars", title: "Wine Bars" },
      { alias: "pizza", title: "Pizza" },
      { alias: "tradamerican", title: "American" },
    ],
    rating: 3.8,
    coordinates: { latitude: 37.288507, longitude: -121.781739849809 },
    transactions: ["delivery"],
    price: "$$",
    location: {
      address1: "5623 Silver Creek Valley Rd",
      address2: "",
      address3: null,
      city: "San Jose",
      zip_code: "95138",
      country: "US",
      state: "CA",
      display_address: ["5623 Silver Creek Valley Rd", "San Jose, CA 95138"],
    },
    phone: "+14084400944",
    display_phone: "(408) 440-0944",
    distance: 9654.409065460779,
  },
  {
    id: "OEcqMG6YRjOZZ0ikjMcP6A",
    alias: "tony-and-albas-pizza-and-pasta-san-jose",
    name: "Tony & Alba's Pizza & Pasta",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/PQVIUzxCWHUf6rge7b1PcA/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/tony-and-albas-pizza-and-pasta-san-jose?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 1200,
    categories: [
      { alias: "pizza", title: "Pizza" },
      { alias: "italian", title: "Italian" },
      { alias: "pastashops", title: "Pasta Shops" },
    ],
    rating: 4.1,
    coordinates: { latitude: 37.3240352860946, longitude: -121.951443841395 },
    transactions: ["pickup", "delivery"],
    price: "$$",
    location: {
      address1: "3137 Stevens Creek Blvd",
      address2: "",
      address3: "",
      city: "San Jose",
      zip_code: "95117",
      country: "US",
      state: "CA",
      display_address: ["3137 Stevens Creek Blvd", "San Jose, CA 95117"],
    },
    phone: "+14082464605",
    display_phone: "(408) 246-4605",
    distance: 5929.082789587882,
  },
  {
    id: "Jf1T_jR4uBpwmOYcwKT--g",
    alias: "simply-pasta-union-city",
    name: "Simply Pasta",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/cnuXt9mDBvtX1KyeFngRLg/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/simply-pasta-union-city?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 146,
    categories: [{ alias: "pastashops", title: "Pasta Shops" }],
    rating: 4.8,
    coordinates: { latitude: 37.5896539, longitude: -122.0675209 },
    transactions: ["pickup", "delivery"],
    location: {
      address1: "32144 Alvarado Blvd",
      address2: null,
      address3: null,
      city: "Union City",
      zip_code: "94587",
      country: "US",
      state: "CA",
      display_address: ["32144 Alvarado Blvd", "Union City, CA 94587"],
    },
    phone: "+15109529421",
    display_phone: "(510) 952-9421",
    distance: 34380.84584245467,
  },
  {
    id: "jx9Bkdqz-euk5OiFYk96pA",
    alias: "the-club-on-post-san-jose",
    name: "The Club On Post",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/z18nUgbaMaLHxc-z9smf4Q/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/the-club-on-post-san-jose?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 96,
    categories: [
      { alias: "newamerican", title: "New American" },
      { alias: "cocktailbars", title: "Cocktail Bars" },
    ],
    rating: 4.6,
    coordinates: { latitude: 37.33524110699076, longitude: -121.8906932 },
    transactions: [],
    location: {
      address1: "43 Post St",
      address2: null,
      address3: "",
      city: "San Jose",
      zip_code: "95113",
      country: "US",
      state: "CA",
      display_address: ["43 Post St", "San Jose, CA 95113"],
    },
    phone: "+14083525286",
    display_phone: "(408) 352-5286",
    distance: 2144.431652497676,
  },
  {
    id: "vZ41QYMBQvtHgpAfw1IToQ",
    alias: "pizza-antica-san-jose",
    name: "Pizza Antica",
    image_url:
      "https://s3-media4.fl.yelpcdn.com/bphoto/FpdfV5t_eLfsqXYqAKP87g/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/pizza-antica-san-jose?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 3468,
    categories: [{ alias: "pizza", title: "Pizza" }],
    rating: 3.8,
    coordinates: {
      latitude: 37.322020736453815,
      longitude: -121.94757693252252,
    },
    transactions: ["delivery"],
    price: "$$",
    location: {
      address1: "334 Santana Row",
      address2: "Ste 1065",
      address3: "",
      city: "San Jose",
      zip_code: "95128",
      country: "US",
      state: "CA",
      display_address: ["334 Santana Row", "Ste 1065", "San Jose, CA 95128"],
    },
    phone: "+14085578373",
    display_phone: "(408) 557-8373",
    distance: 5561.625136855451,
  },
  {
    id: "O0R8TkEE2eWDnp9xOOjHBQ",
    alias: "a-bellagio-italian-restaurant-campbell-2",
    name: "A Bellagio Italian Restaurant",
    image_url:
      "https://s3-media1.fl.yelpcdn.com/bphoto/2dQYnxR2--YXzQgd4cq8oA/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/a-bellagio-italian-restaurant-campbell-2?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 1285,
    categories: [{ alias: "italian", title: "Italian" }],
    rating: 4,
    coordinates: { latitude: 37.2865477562745, longitude: -121.943798480214 },
    transactions: ["restaurant_reservation", "pickup"],
    price: "$$$",
    location: {
      address1: "33 S Central Ave",
      address2: null,
      address3: "",
      city: "Campbell",
      zip_code: "95008",
      country: "US",
      state: "CA",
      display_address: ["33 S Central Ave", "Campbell, CA 95008"],
    },
    phone: "+14083707705",
    display_phone: "(408) 370-7705",
    distance: 6169.391903452878,
  },
  {
    id: "aJORpoQgCfO1-DyK24gTTw",
    alias: "the-old-spaghetti-factory-san-jose-2",
    name: "The Old Spaghetti Factory",
    image_url:
      "https://s3-media1.fl.yelpcdn.com/bphoto/fvVGoM4BqQmkPKoe0m7HhQ/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/the-old-spaghetti-factory-san-jose-2?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 1882,
    categories: [
      { alias: "italian", title: "Italian" },
      { alias: "catering", title: "Caterers" },
    ],
    rating: 3.1,
    coordinates: { latitude: 37.336045, longitude: -121.893779 },
    transactions: ["delivery"],
    price: "$$",
    location: {
      address1: "51 N San Pedro St",
      address2: "",
      address3: "",
      city: "San Jose",
      zip_code: "95110",
      country: "US",
      state: "CA",
      display_address: ["51 N San Pedro St", "San Jose, CA 95110"],
    },
    phone: "+14082887488",
    display_phone: "(408) 288-7488",
    distance: 2307.649401059811,
  },
  {
    id: "QeKutcDiKOjY1-jta4E6uA",
    alias: "maurizios-morgan-hill",
    name: "Maurizio's",
    image_url:
      "https://s3-media1.fl.yelpcdn.com/bphoto/XZH8TAgAD59oENtY6Ses6A/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/maurizios-morgan-hill?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 956,
    categories: [{ alias: "italian", title: "Italian" }],
    rating: 4.5,
    coordinates: { latitude: 37.12994, longitude: -121.653458 },
    transactions: ["restaurant_reservation", "pickup"],
    price: "$$",
    location: {
      address1: "25 E 1st St",
      address2: "",
      address3: "",
      city: "Morgan Hill",
      zip_code: "95037",
      country: "US",
      state: "CA",
      display_address: ["25 E 1st St", "Morgan Hill, CA 95037"],
    },
    phone: "+14087827550",
    display_phone: "(408) 782-7550",
    distance: 29168.63468904467,
  },
  {
    id: "otWXARjK6O5ZCHARUPF2Aw",
    alias: "giorgios-italian-food-san-jose-san-jose",
    name: "Giorgio's Italian Food San Jose",
    image_url:
      "https://s3-media4.fl.yelpcdn.com/bphoto/namLacw-v8eyneUsS7d4Mw/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/giorgios-italian-food-san-jose-san-jose?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 968,
    categories: [
      { alias: "italian", title: "Italian" },
      { alias: "pizza", title: "Pizza" },
      { alias: "bars", title: "Bars" },
    ],
    rating: 3.5,
    coordinates: {
      latitude: 37.27512837389766,
      longitude: -121.89308345823956,
    },
    transactions: ["pickup"],
    price: "$$",
    location: {
      address1: "1445 Foxworthy Ave",
      address2: "",
      address3: "",
      city: "San Jose",
      zip_code: "95118",
      country: "US",
      state: "CA",
      display_address: ["1445 Foxworthy Ave", "San Jose, CA 95118"],
    },
    phone: "+14082645781",
    display_phone: "(408) 264-5781",
    distance: 4652.520009004481,
  },
  {
    id: "nOqKtfPYzYRNRLR1Fb0i8w",
    alias: "la-pizza-and-la-pasta-santa-clara-4",
    name: "La Pizza & La Pasta",
    image_url:
      "https://s3-media4.fl.yelpcdn.com/bphoto/lW2eIVf_EjozXSLJs0INcA/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/la-pizza-and-la-pasta-santa-clara-4?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 1347,
    categories: [
      { alias: "italian", title: "Italian" },
      { alias: "pizza", title: "Pizza" },
      { alias: "cocktailbars", title: "Cocktail Bars" },
    ],
    rating: 3.9,
    coordinates: {
      latitude: 37.32501424089613,
      longitude: -121.94622035695656,
    },
    transactions: [],
    location: {
      address1: "2855 Stevens Creek Blvd",
      address2: "",
      address3: null,
      city: "Santa Clara",
      zip_code: "95050",
      country: "US",
      state: "CA",
      display_address: ["2855 Stevens Creek Blvd", "Santa Clara, CA 95050"],
    },
    phone: "+16504569200",
    display_phone: "(650) 456-9200",
    distance: 5489.955340421734,
  },
  {
    id: "IdG2RWRf_-XDAnaHjbT_hQ",
    alias: "the-pasta-market-san-jose",
    name: "The Pasta Market",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/Z-ztBskTKhl1J1y-b6Tdiw/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/the-pasta-market-san-jose?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 551,
    categories: [
      { alias: "italian", title: "Italian" },
      { alias: "pastashops", title: "Pasta Shops" },
      { alias: "sandwiches", title: "Sandwiches" },
    ],
    rating: 3.3,
    coordinates: { latitude: 37.33973, longitude: -121.907222 },
    transactions: ["pickup", "delivery"],
    price: "$$",
    location: {
      address1: "579 Coleman Ave",
      address2: "",
      address3: "",
      city: "San Jose",
      zip_code: "95110",
      country: "US",
      state: "CA",
      display_address: ["579 Coleman Ave", "San Jose, CA 95110"],
    },
    phone: "+14082886600",
    display_phone: "(408) 288-6600",
    distance: 3243.3172200141366,
  },
  {
    id: "Ahga5g0HufU_G7S1n8WL8g",
    alias: "trattoria-360-campbell",
    name: "Trattoria 360",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/tQjGJl2eakmaqg1u67OqWg/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/trattoria-360-campbell?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 624,
    categories: [
      { alias: "italian", title: "Italian" },
      { alias: "seafood", title: "Seafood" },
    ],
    rating: 4.6,
    coordinates: { latitude: 37.286898, longitude: -121.943741 },
    transactions: ["pickup", "delivery"],
    price: "$$$",
    location: {
      address1: "360 E Campbell Ave",
      address2: "",
      address3: null,
      city: "Campbell",
      zip_code: "95008",
      country: "US",
      state: "CA",
      display_address: ["360 E Campbell Ave", "Campbell, CA 95008"],
    },
    phone: "+14084298671",
    display_phone: "(408) 429-8671",
    distance: 6143.595746936291,
  },
  {
    id: "MOcrD0lJxRiuO9qQjQYRag",
    alias: "siena-bistro-san-jose-2",
    name: "Siena Bistro",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/TvJQsUIJiYCOByZoLaauBA/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/siena-bistro-san-jose-2?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 693,
    categories: [
      { alias: "mediterranean", title: "Mediterranean" },
      { alias: "italian", title: "Italian" },
    ],
    rating: 4.3,
    coordinates: {
      latitude: 37.30392283954612,
      longitude: -121.89844930345522,
    },
    transactions: ["restaurant_reservation", "pickup"],
    price: "$$",
    location: {
      address1: "1359 Lincoln Ave",
      address2: "",
      address3: null,
      city: "San Jose",
      zip_code: "95125",
      country: "US",
      state: "CA",
      display_address: ["1359 Lincoln Ave", "San Jose, CA 95125"],
    },
    phone: "+14082710837",
    display_phone: "(408) 271-0837",
    distance: 1830.2877325602606,
  },
  {
    id: "FQnIs9ojngandeHW4UrasA",
    alias: "california-soul-food-newark-2",
    name: "California Soul Food",
    image_url:
      "https://s3-media1.fl.yelpcdn.com/bphoto/jbQdTWGtyfm4JNGosr000w/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/california-soul-food-newark-2?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 3,
    categories: [
      { alias: "bbq", title: "Barbeque" },
      { alias: "soulfood", title: "Soul Food" },
      { alias: "fooddeliveryservices", title: "Food Delivery Services" },
    ],
    rating: 5,
    coordinates: { latitude: 37.53379, longitude: -122.0341 },
    transactions: ["pickup", "delivery"],
    location: {
      address1: "36976 Cherry St",
      address2: null,
      address3: "",
      city: "Newark",
      zip_code: "94560",
      country: "US",
      state: "CA",
      display_address: ["36976 Cherry St", "Newark, CA 94560"],
    },
    phone: "+14085027411",
    display_phone: "(408) 502-7411",
    distance: 27517.687158294906,
  },
  {
    id: "kyCAxIcS_axZB12EtHV1FA",
    alias: "olive-garden-italian-restaurant-san-jose-7",
    name: "Olive Garden Italian Restaurant",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/y2A9ww18GyV5glN_tCgjMg/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/olive-garden-italian-restaurant-san-jose-7?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 511,
    categories: [
      { alias: "italian", title: "Italian" },
      { alias: "salad", title: "Salad" },
      { alias: "soup", title: "Soup" },
    ],
    rating: 3,
    coordinates: { latitude: 37.32565, longitude: -121.81072269386576 },
    transactions: [],
    price: "$$",
    location: {
      address1: "2226 Eastridge Lp",
      address2: "",
      address3: "",
      city: "San Jose",
      zip_code: "95122",
      country: "US",
      state: "CA",
      display_address: ["2226 Eastridge Lp", "San Jose, CA 95122"],
    },
    phone: "+14082742447",
    display_phone: "(408) 274-2447",
    distance: 6653.016494894222,
  },
  {
    id: "4f8bHCUYwEn_6dLlQxZwGg",
    alias: "vitos-trattoria-san-jose",
    name: "Vito's Trattoria",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/DLYOff6aA12_40S7UJV3zQ/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/vitos-trattoria-san-jose?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 807,
    categories: [
      { alias: "italian", title: "Italian" },
      { alias: "bars", title: "Bars" },
      { alias: "pizza", title: "Pizza" },
    ],
    rating: 4.1,
    coordinates: { latitude: 37.365367, longitude: -121.916016 },
    transactions: ["pickup", "delivery"],
    price: "$$$",
    location: {
      address1: "90 Skyport Dr",
      address2: "",
      address3: "",
      city: "San Jose",
      zip_code: "95110",
      country: "US",
      state: "CA",
      display_address: ["90 Skyport Dr", "San Jose, CA 95110"],
    },
    phone: "+14084531000",
    display_phone: "(408) 453-1000",
    distance: 6085.432562002565,
  },
  {
    id: "dhgpgveMAPtmaan72IbFaA",
    alias: "inkas-restaurant-san-jose-2",
    name: "Inka's Restaurant",
    image_url:
      "https://s3-media1.fl.yelpcdn.com/bphoto/zHM8hfYBjC2km3otZZ1hTA/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/inkas-restaurant-san-jose-2?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 186,
    categories: [
      { alias: "peruvian", title: "Peruvian" },
      { alias: "seafood", title: "Seafood" },
    ],
    rating: 4.6,
    coordinates: { latitude: 37.31474037278964, longitude: -121.9494886 },
    transactions: ["restaurant_reservation"],
    price: "$$",
    location: {
      address1: "700 S Winchester Blvd",
      address2: "Ste 25",
      address3: null,
      city: "San Jose",
      zip_code: "95128",
      country: "US",
      state: "CA",
      display_address: [
        "700 S Winchester Blvd",
        "Ste 25",
        "San Jose, CA 95128",
      ],
    },
    phone: "+14083202134",
    display_phone: "(408) 320-2134",
    distance: 5700.021103672855,
  },
  {
    id: "7st8Szc_Z4Oqz1dEI1EpLw",
    alias: "il-fornaio-mountain-view",
    name: "Il Fornaio",
    image_url:
      "https://s3-media4.fl.yelpcdn.com/bphoto/fslqtY88O0H6uyy5MS8Acg/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/il-fornaio-mountain-view?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 267,
    categories: [{ alias: "italian", title: "Italian" }],
    rating: 4.5,
    coordinates: {
      latitude: 37.403342872081346,
      longitude: -122.11201180334038,
    },
    transactions: ["pickup", "delivery"],
    location: {
      address1: "545 San Antonio Rd",
      address2: "Ste 31",
      address3: null,
      city: "Mountain View",
      zip_code: "94040",
      country: "US",
      state: "CA",
      display_address: [
        "545 San Antonio Rd",
        "Ste 31",
        "Mountain View, CA 94040",
      ],
    },
    phone: "+16505675100",
    display_phone: "(650) 567-5100",
    distance: 22261.872769929872,
  },
  {
    id: "iaSxupFUUGpGPFOGMoTL_g",
    alias: "the-crab-bay-san-jose-2",
    name: "The Crab Bay",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/aWyLBi14WO9zwZeVl_kv9w/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/the-crab-bay-san-jose-2?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 518,
    categories: [
      { alias: "cajun", title: "Cajun/Creole" },
      { alias: "seafood", title: "Seafood" },
      { alias: "desserts", title: "Desserts" },
    ],
    rating: 4,
    coordinates: { latitude: 37.315437170137606, longitude: -121.7921522 },
    transactions: [],
    price: "$$",
    location: {
      address1: "3210 S White Rd",
      address2: null,
      address3: "",
      city: "San Jose",
      zip_code: "95148",
      country: "US",
      state: "CA",
      display_address: ["3210 S White Rd", "San Jose, CA 95148"],
    },
    phone: "+14089829999",
    display_phone: "(408) 982-9999",
    distance: 8217.959462983046,
  },
  {
    id: "1uOJSq_h7yPOKExVLeKL_A",
    alias: "angelos-italian-restaurant-and-pizza-san-jose",
    name: "Angelo's Italian Restaurant & Pizza",
    image_url:
      "https://s3-media4.fl.yelpcdn.com/bphoto/1eUFHizLJ7g1hykHX3IpPA/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/angelos-italian-restaurant-and-pizza-san-jose?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 364,
    categories: [
      { alias: "italian", title: "Italian" },
      { alias: "pizza", title: "Pizza" },
      { alias: "pastashops", title: "Pasta Shops" },
    ],
    rating: 3.8,
    coordinates: { latitude: 37.2501529182473, longitude: -121.829755209787 },
    transactions: ["pickup"],
    price: "$$",
    location: {
      address1: "436 Blossom Hill Rd",
      address2: null,
      address3: "",
      city: "San Jose",
      zip_code: "95123",
      country: "US",
      state: "CA",
      display_address: ["436 Blossom Hill Rd", "San Jose, CA 95123"],
    },
    phone: "+14082275502",
    display_phone: "(408) 227-5502",
    distance: 8851.327513485588,
  },
  {
    id: "berEiBE0fDM-HiYFEAf-Ww",
    alias: "goodtime-bar-san-jose",
    name: "Goodtime Bar",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/lEEjBtL6qaBCYS_BC2CrnA/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/goodtime-bar-san-jose?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 130,
    categories: [
      { alias: "wine_bars", title: "Wine Bars" },
      { alias: "tapasmallplates", title: "Tapas/Small Plates" },
      { alias: "seafood", title: "Seafood" },
    ],
    rating: 4.8,
    coordinates: {
      latitude: 37.336240164756504,
      longitude: -121.88963391534423,
    },
    transactions: [],
    price: "$$",
    location: {
      address1: "30 Fountain Alley",
      address2: "Ste 160",
      address3: null,
      city: "San Jose",
      zip_code: "95113",
      country: "US",
      state: "CA",
      display_address: ["30 Fountain Alley", "Ste 160", "San Jose, CA 95113"],
    },
    phone: "+14082561266",
    display_phone: "(408) 256-1266",
    distance: 2233.839603693528,
  },
  {
    id: "_SJMOWdVrYkQFZMkC1oDEg",
    alias: "pasta-amore-san-jose",
    name: "Pasta Amore",
    image_url:
      "https://s3-media4.fl.yelpcdn.com/bphoto/4XoTNFRt1A408DTPNn1qnQ/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/pasta-amore-san-jose?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 42,
    categories: [
      { alias: "foodtrucks", title: "Food Trucks" },
      { alias: "italian", title: "Italian" },
    ],
    rating: 4.4,
    coordinates: { latitude: 37.359787, longitude: -121.903035 },
    transactions: ["pickup", "delivery"],
    price: "$$",
    location: {
      address1: "1160 North 4th St",
      address2: null,
      address3: "",
      city: "San jose",
      zip_code: "95112",
      country: "US",
      state: "CA",
      display_address: ["1160 North 4th St", "San jose, CA 95112"],
    },
    phone: "",
    display_phone: "",
    distance: 5066.2218567320315,
  },
  {
    id: "hxeRSr57nAosHaKPJzMltw",
    alias: "la-pizzeria-cupertino-cupertino",
    name: "La Pizzeria Cupertino",
    image_url:
      "https://s3-media1.fl.yelpcdn.com/bphoto/laNvxaAFWnaFCqkf3Gt6og/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/la-pizzeria-cupertino-cupertino?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 220,
    categories: [
      { alias: "italian", title: "Italian" },
      { alias: "vegan", title: "Vegan" },
      { alias: "pizza", title: "Pizza" },
    ],
    rating: 4,
    coordinates: { latitude: 37.3247704743891, longitude: -122.0139185 },
    transactions: ["restaurant_reservation", "delivery"],
    price: "$$",
    location: {
      address1: "10088 N Wolfe Rd",
      address2: "Ste 120",
      address3: "",
      city: "Cupertino",
      zip_code: "95014",
      country: "US",
      state: "CA",
      display_address: ["10088 N Wolfe Rd", "Ste 120", "Cupertino, CA 95014"],
    },
    phone: "+14088630308",
    display_phone: "(408) 863-0308",
    distance: 11430.998282190198,
  },
  {
    id: "gEm6xu9uzF3bewoO0FX2Tw",
    alias: "centonove-los-gatos",
    name: "Centonove",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/oX_p02SLlJtGZDov07GtKQ/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/centonove-los-gatos?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 856,
    categories: [
      { alias: "italian", title: "Italian" },
      { alias: "wine_bars", title: "Wine Bars" },
      { alias: "pizza", title: "Pizza" },
    ],
    rating: 3.9,
    coordinates: { latitude: 37.22188, longitude: -121.98307 },
    transactions: ["restaurant_reservation", "pickup", "delivery"],
    price: "$$",
    location: {
      address1: "109 W Main St",
      address2: null,
      address3: "",
      city: "Los Gatos",
      zip_code: "95030",
      country: "US",
      state: "CA",
      display_address: ["109 W Main St", "Los Gatos, CA 95030"],
    },
    phone: "+14083844007",
    display_phone: "(408) 384-4007",
    distance: 13626.555836692985,
  },
  {
    id: "4Pr1G5olABPmItHKWqtyew",
    alias: "al-castello-ristorante-and-pizzeria-san-jose",
    name: "Al Castello Ristorante & Pizzeria",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/UBZ31MpMepx1RniLQsp3mA/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/al-castello-ristorante-and-pizzeria-san-jose?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 483,
    categories: [
      { alias: "italian", title: "Italian" },
      { alias: "pizza", title: "Pizza" },
      { alias: "seafood", title: "Seafood" },
    ],
    rating: 4,
    coordinates: { latitude: 37.262792, longitude: -121.93519 },
    transactions: ["pickup", "delivery"],
    price: "$$",
    location: {
      address1: "2083 Camden Ave",
      address2: "",
      address3: "",
      city: "San Jose",
      zip_code: "95124",
      country: "US",
      state: "CA",
      display_address: ["2083 Camden Ave", "San Jose, CA 95124"],
    },
    phone: "+14083699820",
    display_phone: "(408) 369-9820",
    distance: 7455.402946482622,
  },
  {
    id: "K-zrwN1osIDdQSEbyKnn4w",
    alias: "tomatina-san-jose-2",
    name: "Tomatina",
    image_url:
      "https://s3-media1.fl.yelpcdn.com/bphoto/-SP07zTy1FTXjebq-aeozQ/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/tomatina-san-jose-2?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 390,
    categories: [
      { alias: "italian", title: "Italian" },
      { alias: "pizza", title: "Pizza" },
      { alias: "salad", title: "Salad" },
    ],
    rating: 3,
    coordinates: { latitude: 37.29238, longitude: -121.99377 },
    transactions: ["delivery"],
    price: "$$",
    location: {
      address1: "5245 Prospect Rd",
      address2: "",
      address3: "",
      city: "San Jose",
      zip_code: "95129",
      country: "US",
      state: "CA",
      display_address: ["5245 Prospect Rd", "San Jose, CA 95129"],
    },
    phone: "+14083800040",
    display_phone: "(408) 380-0040",
    distance: 9978.350104148967,
  },
  {
    id: "eiOviOLjM_tBInEXP2VpNg",
    alias: "milan-san-jose-2",
    name: "Milan",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/PUZ2oPd1ftruvHbUMKucQQ/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/milan-san-jose-2?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 145,
    categories: [{ alias: "italian", title: "Italian" }],
    rating: 4.2,
    coordinates: { latitude: 37.292268, longitude: -121.912447 },
    transactions: ["restaurant_reservation"],
    location: {
      address1: "1712 Meridian Ave",
      address2: "Ste F",
      address3: "",
      city: "San Jose",
      zip_code: "95125",
      country: "US",
      state: "CA",
      display_address: ["1712 Meridian Ave", "Ste F", "San Jose, CA 95125"],
    },
    phone: "+14086774096",
    display_phone: "(408) 677-4096",
    distance: 3630.306382778759,
  },
  {
    id: "L9AWF6AYvOghYFNBoP445Q",
    alias: "buca-di-beppo-italian-restaurant-campbell-2",
    name: "Buca di Beppo Italian Restaurant",
    image_url:
      "https://s3-media4.fl.yelpcdn.com/bphoto/6s3Omp9tkUUALXG1QMvWVQ/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/buca-di-beppo-italian-restaurant-campbell-2?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 1345,
    categories: [{ alias: "italian", title: "Italian" }],
    rating: 2.9,
    coordinates: { latitude: 37.28844937443894, longitude: -121.9337906327934 },
    transactions: ["pickup", "delivery"],
    price: "$$",
    location: {
      address1: "1875 S Bascom Ave",
      address2: "",
      address3: "",
      city: "Campbell",
      zip_code: "95008",
      country: "US",
      state: "CA",
      display_address: ["1875 S Bascom Ave", "Campbell, CA 95008"],
    },
    phone: "+14083777722",
    display_phone: "(408) 377-7722",
    distance: 5318.3883190769675,
  },
  {
    id: "jw9hoVTHWsNYnFaFt9tnow",
    alias: "campo-di-bocce-of-los-gatos-los-gatos",
    name: "Campo Di Bocce of Los Gatos",
    image_url:
      "https://s3-media4.fl.yelpcdn.com/bphoto/x2d2l3I2rT2gddgoWU1khA/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/campo-di-bocce-of-los-gatos-los-gatos?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 619,
    categories: [
      { alias: "italian", title: "Italian" },
      { alias: "bocceball", title: "Bocce Ball" },
      { alias: "venues", title: "Venues & Event Spaces" },
    ],
    rating: 4,
    coordinates: { latitude: 37.232282645501954, longitude: -121.9779096 },
    transactions: ["pickup", "delivery"],
    price: "$$",
    location: {
      address1: "565 University Ave",
      address2: "",
      address3: "",
      city: "Los Gatos",
      zip_code: "95032",
      country: "US",
      state: "CA",
      display_address: ["565 University Ave", "Los Gatos, CA 95032"],
    },
    phone: "+14083957650",
    display_phone: "(408) 395-7650",
    distance: 12455.327810223504,
  },
  {
    id: "JG1T2nEoCPJ7drd1ZnG8GQ",
    alias: "tomato-thyme-san-jose-3",
    name: "Tomato Thyme",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/XGpgJBP8IYL-J1TVi1aI0A/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/tomato-thyme-san-jose-3?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 707,
    categories: [
      { alias: "pizza", title: "Pizza" },
      { alias: "salad", title: "Salad" },
      { alias: "pastashops", title: "Pasta Shops" },
    ],
    rating: 3.7,
    coordinates: { latitude: 37.29362, longitude: -121.91223 },
    transactions: ["pickup", "delivery"],
    price: "$$",
    location: {
      address1: "1560 Hamilton Ave",
      address2: "",
      address3: "",
      city: "San Jose",
      zip_code: "95125",
      country: "US",
      state: "CA",
      display_address: ["1560 Hamilton Ave", "San Jose, CA 95125"],
    },
    phone: "+14087237333",
    display_phone: "(408) 723-7333",
    distance: 3500.272319661178,
  },
  {
    id: "hl2yriEDrXYTj1XFjaImGg",
    alias: "fambrinis-cafe-palo-alto",
    name: "Fambrini's Cafe",
    image_url:
      "https://s3-media4.fl.yelpcdn.com/bphoto/Gqa-WyfVpe0NTu8OMvutag/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/fambrinis-cafe-palo-alto?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 1413,
    categories: [
      { alias: "sandwiches", title: "Sandwiches" },
      { alias: "breakfast_brunch", title: "Breakfast & Brunch" },
      { alias: "salad", title: "Salad" },
    ],
    rating: 4.4,
    coordinates: { latitude: 37.42404, longitude: -122.14513 },
    transactions: ["pickup", "delivery"],
    price: "$$",
    location: {
      address1: "2500 El Camino Real",
      address2: "",
      address3: "",
      city: "Palo Alto",
      zip_code: "94306",
      country: "US",
      state: "CA",
      display_address: ["2500 El Camino Real", "Palo Alto, CA 94306"],
    },
    phone: "+16508581268",
    display_phone: "(650) 858-1268",
    distance: 25913.944566268532,
  },
  {
    id: "PCUzAxUa0jzFCIpSFwwzpQ",
    alias: "la-pizzeria-campbell",
    name: "La Pizzeria",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/089KCNdQokZ6N1eFLFSO8w/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/la-pizzeria-campbell?adjust_creative=bbssY1jLXoaM68ToDodjSw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=bbssY1jLXoaM68ToDodjSw",
    review_count: 919,
    categories: [
      { alias: "pizza", title: "Pizza" },
      { alias: "italian", title: "Italian" },
    ],
    rating: 3.9,
    coordinates: { latitude: 37.2871531, longitude: -121.9432429 },
    transactions: ["restaurant_reservation", "delivery"],
    price: "$$",
    location: {
      address1: "373 E Campbell Ave",
      address2: null,
      address3: "",
      city: "Campbell",
      zip_code: "95008",
      country: "US",
      state: "CA",
      display_address: ["373 E Campbell Ave", "Campbell, CA 95008"],
    },
    phone: "+14083700826",
    display_phone: "(408) 370-0826",
    distance: 6091.758052376952,
  },
];
